print("===== PC VIRTUAL =====")
print("CPU: AMD Ryzen 7 7800X3D")
print("GPU: NVIDIA GeForce RTX 4070 SUPER 12 GB")
print("RAM: 32 GB")
print("SSD: 1 TB")
print("Sistema: Windows 11")
print("Status: PC ligado")
print("======================")
